from __future__ import print_function

import renpy


# Generated by scripts/relative_imports.py, do not edit below this line.
import typing

if typing.TYPE_CHECKING:
    from . import assimp as assimp
    from . import gl2debug as gl2debug
    from . import gl2draw as gl2draw
    from . import gl2functions as gl2functions
    from . import gl2mesh as gl2mesh
    from . import gl2mesh2 as gl2mesh2
    from . import gl2mesh3 as gl2mesh3
    from . import gl2model as gl2model
    from . import gl2polygon as gl2polygon
    from . import gl2shader as gl2shader
    from . import gl2shadercache as gl2shadercache
    from . import gl2texture as gl2texture
    from . import gl2uniform as gl2uniform
    from . import live2d as live2d
    from . import live2dmodel as live2dmodel
    from . import live2dmotion as live2dmotion
