executable_name = 'the_question'
documentation_extensions = 'txt html'
description = "A simple and complete Ren'Py game."
build_mac = True
build_windows = False
distribution_base = 'the_question-1.0'
ignore_extensions = '~ .bak'
build_linux = False
build_all = False
