from __future__ import print_function

import renpy

from renpy.uguu.uguu import *


# Generated by scripts/relative_imports.py, do not edit below this line.
import typing

if typing.TYPE_CHECKING:
    from . import gl as gl
    from . import uguu as uguu
