# Copyright 2004-2026 Tom Rothamel <pytom@bishoujo.us>
#
# Permission is hereby granted, free of charge, to any person
# obtaining a copy of this software and associated documentation files
# (the "Software"), to deal in the Software without restriction,
# including without limitation the rights to use, copy, modify, merge,
# publish, distribute, sublicense, and/or sell copies of the Software,
# and to permit persons to whom the Software is furnished to do so,
# subject to the following conditions:
#
# The above copyright notice and this permission notice shall be
# included in all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
# EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
# MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
# NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE
# LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION
# OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION
# WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.

# This file is generated by scripts/uguu/xml_to_pyx.py

from renpy.pygame.sdl cimport SDL_GL_GetProcAddress, SDL_GetError

found_functions = set()

cdef void *find_gl_command(names: list[bytes]):

    cdef void *rv = NULL
    cdef str name = names[0].decode("utf-8")

    for i in names:
        rv = SDL_GL_GetProcAddress(i)

        if rv != NULL:
            found_functions.add(name)
            return rv

    cdef const char *message = SDL_GetError()

    import renpy
    renpy.display.log.write(f"UGUU couldn't find {name}: {message.decode("utf-8", "replace")}")

    return NULL

def clear_missing_functions():
    found_functions.clear()

def check_missing_functions(required):
    import renpy

    required = set(required)

    missing_required = list(required - found_functions)
    missing_required.sort()

    if missing_required:
        renpy.display.log.write("The following gl functions are missing:")
        for i in missing_required:
            renpy.display.log.write(f"- {i}")

        return True
    else:
        return False

cdef:
    glActiveTexture_type glActiveTexture
    glAttachShader_type glAttachShader
    glBeginQuery_type glBeginQuery
    glBeginTransformFeedback_type glBeginTransformFeedback
    glBindAttribLocation_type glBindAttribLocation
    glBindBuffer_type glBindBuffer
    glBindBufferBase_type glBindBufferBase
    glBindBufferRange_type glBindBufferRange
    glBindFramebuffer_type glBindFramebuffer
    glBindRenderbuffer_type glBindRenderbuffer
    glBindTexture_type glBindTexture
    glBindVertexArray_type glBindVertexArray
    glBlendColor_type glBlendColor
    glBlendEquation_type glBlendEquation
    glBlendEquationSeparate_type glBlendEquationSeparate
    glBlendFunc_type glBlendFunc
    glBlendFuncSeparate_type glBlendFuncSeparate
    glBlitFramebuffer_type glBlitFramebuffer
    glBufferData_type glBufferData
    glBufferSubData_type glBufferSubData
    glCheckFramebufferStatus_type glCheckFramebufferStatus
    glClear_type glClear
    glClearBufferfi_type glClearBufferfi
    glClearBufferfv_type glClearBufferfv
    glClearBufferiv_type glClearBufferiv
    glClearBufferuiv_type glClearBufferuiv
    glClearColor_type glClearColor
    glClearStencil_type glClearStencil
    glColorMask_type glColorMask
    glCompileShader_type glCompileShader
    glCompressedTexImage2D_type glCompressedTexImage2D
    glCompressedTexImage3D_type glCompressedTexImage3D
    glCompressedTexSubImage2D_type glCompressedTexSubImage2D
    glCompressedTexSubImage3D_type glCompressedTexSubImage3D
    glCopyTexImage2D_type glCopyTexImage2D
    glCopyTexSubImage2D_type glCopyTexSubImage2D
    glCopyTexSubImage3D_type glCopyTexSubImage3D
    glCreateProgram_type glCreateProgram
    glCreateShader_type glCreateShader
    glCullFace_type glCullFace
    glDeleteBuffers_type glDeleteBuffers
    glDeleteFramebuffers_type glDeleteFramebuffers
    glDeleteProgram_type glDeleteProgram
    glDeleteQueries_type glDeleteQueries
    glDeleteRenderbuffers_type glDeleteRenderbuffers
    glDeleteShader_type glDeleteShader
    glDeleteTextures_type glDeleteTextures
    glDeleteVertexArrays_type glDeleteVertexArrays
    glDepthFunc_type glDepthFunc
    glDepthMask_type glDepthMask
    glDetachShader_type glDetachShader
    glDisable_type glDisable
    glDisableVertexAttribArray_type glDisableVertexAttribArray
    glDrawArrays_type glDrawArrays
    glDrawBuffers_type glDrawBuffers
    glDrawElements_type glDrawElements
    glDrawRangeElements_type glDrawRangeElements
    glEnable_type glEnable
    glEnableVertexAttribArray_type glEnableVertexAttribArray
    glEndQuery_type glEndQuery
    glEndTransformFeedback_type glEndTransformFeedback
    glFinish_type glFinish
    glFlush_type glFlush
    glFlushMappedBufferRange_type glFlushMappedBufferRange
    glFramebufferRenderbuffer_type glFramebufferRenderbuffer
    glFramebufferTexture2D_type glFramebufferTexture2D
    glFramebufferTextureLayer_type glFramebufferTextureLayer
    glFrontFace_type glFrontFace
    glGenBuffers_type glGenBuffers
    glGenFramebuffers_type glGenFramebuffers
    glGenQueries_type glGenQueries
    glGenRenderbuffers_type glGenRenderbuffers
    glGenTextures_type glGenTextures
    glGenVertexArrays_type glGenVertexArrays
    glGenerateMipmap_type glGenerateMipmap
    glGetActiveAttrib_type glGetActiveAttrib
    glGetActiveUniform_type glGetActiveUniform
    glGetAttachedShaders_type glGetAttachedShaders
    glGetAttribLocation_type glGetAttribLocation
    glGetBooleanv_type glGetBooleanv
    glGetBufferParameteriv_type glGetBufferParameteriv
    glGetBufferPointerv_type glGetBufferPointerv
    glGetError_type glGetError
    glGetFloatv_type glGetFloatv
    glGetFragDataLocation_type glGetFragDataLocation
    glGetFramebufferAttachmentParameteriv_type glGetFramebufferAttachmentParameteriv
    glGetIntegeri_v_type glGetIntegeri_v
    glGetIntegerv_type glGetIntegerv
    glGetProgramInfoLog_type glGetProgramInfoLog
    glGetProgramiv_type glGetProgramiv
    glGetQueryObjectuiv_type glGetQueryObjectuiv
    glGetQueryiv_type glGetQueryiv
    glGetRenderbufferParameteriv_type glGetRenderbufferParameteriv
    glGetShaderInfoLog_type glGetShaderInfoLog
    glGetShaderSource_type glGetShaderSource
    glGetShaderiv_type glGetShaderiv
    glGetString_type glGetString
    glGetStringi_type glGetStringi
    glGetTexParameterfv_type glGetTexParameterfv
    glGetTexParameteriv_type glGetTexParameteriv
    glGetTransformFeedbackVarying_type glGetTransformFeedbackVarying
    glGetUniformLocation_type glGetUniformLocation
    glGetUniformfv_type glGetUniformfv
    glGetUniformiv_type glGetUniformiv
    glGetUniformuiv_type glGetUniformuiv
    glGetVertexAttribIiv_type glGetVertexAttribIiv
    glGetVertexAttribIuiv_type glGetVertexAttribIuiv
    glGetVertexAttribPointerv_type glGetVertexAttribPointerv
    glGetVertexAttribfv_type glGetVertexAttribfv
    glGetVertexAttribiv_type glGetVertexAttribiv
    glHint_type glHint
    glIsBuffer_type glIsBuffer
    glIsEnabled_type glIsEnabled
    glIsFramebuffer_type glIsFramebuffer
    glIsProgram_type glIsProgram
    glIsQuery_type glIsQuery
    glIsRenderbuffer_type glIsRenderbuffer
    glIsShader_type glIsShader
    glIsTexture_type glIsTexture
    glIsVertexArray_type glIsVertexArray
    glLineWidth_type glLineWidth
    glLinkProgram_type glLinkProgram
    glMapBufferRange_type glMapBufferRange
    glPixelStorei_type glPixelStorei
    glPolygonOffset_type glPolygonOffset
    glReadBuffer_type glReadBuffer
    glReadPixels_type glReadPixels
    glRenderbufferStorage_type glRenderbufferStorage
    glRenderbufferStorageMultisample_type glRenderbufferStorageMultisample
    glSampleCoverage_type glSampleCoverage
    glScissor_type glScissor
    glShaderSource_type glShaderSource
    glStencilFunc_type glStencilFunc
    glStencilFuncSeparate_type glStencilFuncSeparate
    glStencilMask_type glStencilMask
    glStencilMaskSeparate_type glStencilMaskSeparate
    glStencilOp_type glStencilOp
    glStencilOpSeparate_type glStencilOpSeparate
    glTexImage2D_type glTexImage2D
    glTexImage3D_type glTexImage3D
    glTexParameterf_type glTexParameterf
    glTexParameterfv_type glTexParameterfv
    glTexParameteri_type glTexParameteri
    glTexParameteriv_type glTexParameteriv
    glTexSubImage2D_type glTexSubImage2D
    glTexSubImage3D_type glTexSubImage3D
    glTransformFeedbackVaryings_type glTransformFeedbackVaryings
    glUniform1f_type glUniform1f
    glUniform1fv_type glUniform1fv
    glUniform1i_type glUniform1i
    glUniform1iv_type glUniform1iv
    glUniform1ui_type glUniform1ui
    glUniform1uiv_type glUniform1uiv
    glUniform2f_type glUniform2f
    glUniform2fv_type glUniform2fv
    glUniform2i_type glUniform2i
    glUniform2iv_type glUniform2iv
    glUniform2ui_type glUniform2ui
    glUniform2uiv_type glUniform2uiv
    glUniform3f_type glUniform3f
    glUniform3fv_type glUniform3fv
    glUniform3i_type glUniform3i
    glUniform3iv_type glUniform3iv
    glUniform3ui_type glUniform3ui
    glUniform3uiv_type glUniform3uiv
    glUniform4f_type glUniform4f
    glUniform4fv_type glUniform4fv
    glUniform4i_type glUniform4i
    glUniform4iv_type glUniform4iv
    glUniform4ui_type glUniform4ui
    glUniform4uiv_type glUniform4uiv
    glUniformMatrix2fv_type glUniformMatrix2fv
    glUniformMatrix2x3fv_type glUniformMatrix2x3fv
    glUniformMatrix2x4fv_type glUniformMatrix2x4fv
    glUniformMatrix3fv_type glUniformMatrix3fv
    glUniformMatrix3x2fv_type glUniformMatrix3x2fv
    glUniformMatrix3x4fv_type glUniformMatrix3x4fv
    glUniformMatrix4fv_type glUniformMatrix4fv
    glUniformMatrix4x2fv_type glUniformMatrix4x2fv
    glUniformMatrix4x3fv_type glUniformMatrix4x3fv
    glUnmapBuffer_type glUnmapBuffer
    glUseProgram_type glUseProgram
    glValidateProgram_type glValidateProgram
    glVertexAttrib1f_type glVertexAttrib1f
    glVertexAttrib1fv_type glVertexAttrib1fv
    glVertexAttrib2f_type glVertexAttrib2f
    glVertexAttrib2fv_type glVertexAttrib2fv
    glVertexAttrib3f_type glVertexAttrib3f
    glVertexAttrib3fv_type glVertexAttrib3fv
    glVertexAttrib4f_type glVertexAttrib4f
    glVertexAttrib4fv_type glVertexAttrib4fv
    glVertexAttribI4i_type glVertexAttribI4i
    glVertexAttribI4iv_type glVertexAttribI4iv
    glVertexAttribI4ui_type glVertexAttribI4ui
    glVertexAttribI4uiv_type glVertexAttribI4uiv
    glVertexAttribIPointer_type glVertexAttribIPointer
    glVertexAttribPointer_type glVertexAttribPointer
    glViewport_type glViewport

def load():

    global glActiveTexture
    glActiveTexture = <glActiveTexture_type> find_gl_command([b'glActiveTexture', b'glActiveTextureARB'])

    global glAttachShader
    glAttachShader = <glAttachShader_type> find_gl_command([b'glAttachShader'])

    global glBeginQuery
    glBeginQuery = <glBeginQuery_type> find_gl_command([b'glBeginQuery', b'glBeginQueryARB'])

    global glBeginTransformFeedback
    glBeginTransformFeedback = <glBeginTransformFeedback_type> find_gl_command([b'glBeginTransformFeedback', b'glBeginTransformFeedbackEXT', b'glBeginTransformFeedbackNV'])

    global glBindAttribLocation
    glBindAttribLocation = <glBindAttribLocation_type> find_gl_command([b'glBindAttribLocation', b'glBindAttribLocationARB'])

    global glBindBuffer
    glBindBuffer = <glBindBuffer_type> find_gl_command([b'glBindBuffer', b'glBindBufferARB'])

    global glBindBufferBase
    glBindBufferBase = <glBindBufferBase_type> find_gl_command([b'glBindBufferBase', b'glBindBufferBaseEXT', b'glBindBufferBaseNV'])

    global glBindBufferRange
    glBindBufferRange = <glBindBufferRange_type> find_gl_command([b'glBindBufferRange', b'glBindBufferRangeEXT', b'glBindBufferRangeNV'])

    global glBindFramebuffer
    glBindFramebuffer = <glBindFramebuffer_type> find_gl_command([b'glBindFramebuffer', b'glBindFramebufferEXT'])

    global glBindRenderbuffer
    glBindRenderbuffer = <glBindRenderbuffer_type> find_gl_command([b'glBindRenderbuffer', b'glBindRenderbufferEXT'])

    global glBindTexture
    glBindTexture = <glBindTexture_type> find_gl_command([b'glBindTexture', b'glBindTextureEXT'])

    global glBindVertexArray
    glBindVertexArray = <glBindVertexArray_type> find_gl_command([b'glBindVertexArray', b'glBindVertexArrayOES'])

    global glBlendColor
    glBlendColor = <glBlendColor_type> find_gl_command([b'glBlendColor', b'glBlendColorEXT'])

    global glBlendEquation
    glBlendEquation = <glBlendEquation_type> find_gl_command([b'glBlendEquation', b'glBlendEquationEXT'])

    global glBlendEquationSeparate
    glBlendEquationSeparate = <glBlendEquationSeparate_type> find_gl_command([b'glBlendEquationSeparate', b'glBlendEquationSeparateEXT'])

    global glBlendFunc
    glBlendFunc = <glBlendFunc_type> find_gl_command([b'glBlendFunc'])

    global glBlendFuncSeparate
    glBlendFuncSeparate = <glBlendFuncSeparate_type> find_gl_command([b'glBlendFuncSeparate', b'glBlendFuncSeparateEXT', b'glBlendFuncSeparateINGR'])

    global glBlitFramebuffer
    glBlitFramebuffer = <glBlitFramebuffer_type> find_gl_command([b'glBlitFramebuffer', b'glBlitFramebufferEXT', b'glBlitFramebufferNV'])

    global glBufferData
    glBufferData = <glBufferData_type> find_gl_command([b'glBufferData', b'glBufferDataARB'])

    global glBufferSubData
    glBufferSubData = <glBufferSubData_type> find_gl_command([b'glBufferSubData', b'glBufferSubDataARB'])

    global glCheckFramebufferStatus
    glCheckFramebufferStatus = <glCheckFramebufferStatus_type> find_gl_command([b'glCheckFramebufferStatus', b'glCheckFramebufferStatusEXT'])

    global glClear
    glClear = <glClear_type> find_gl_command([b'glClear'])

    global glClearBufferfi
    glClearBufferfi = <glClearBufferfi_type> find_gl_command([b'glClearBufferfi'])

    global glClearBufferfv
    glClearBufferfv = <glClearBufferfv_type> find_gl_command([b'glClearBufferfv'])

    global glClearBufferiv
    glClearBufferiv = <glClearBufferiv_type> find_gl_command([b'glClearBufferiv'])

    global glClearBufferuiv
    glClearBufferuiv = <glClearBufferuiv_type> find_gl_command([b'glClearBufferuiv'])

    global glClearColor
    glClearColor = <glClearColor_type> find_gl_command([b'glClearColor'])

    global glClearStencil
    glClearStencil = <glClearStencil_type> find_gl_command([b'glClearStencil'])

    global glColorMask
    glColorMask = <glColorMask_type> find_gl_command([b'glColorMask'])

    global glCompileShader
    glCompileShader = <glCompileShader_type> find_gl_command([b'glCompileShader', b'glCompileShaderARB'])

    global glCompressedTexImage2D
    glCompressedTexImage2D = <glCompressedTexImage2D_type> find_gl_command([b'glCompressedTexImage2D', b'glCompressedTexImage2DARB'])

    global glCompressedTexImage3D
    glCompressedTexImage3D = <glCompressedTexImage3D_type> find_gl_command([b'glCompressedTexImage3D', b'glCompressedTexImage3DARB'])

    global glCompressedTexSubImage2D
    glCompressedTexSubImage2D = <glCompressedTexSubImage2D_type> find_gl_command([b'glCompressedTexSubImage2D', b'glCompressedTexSubImage2DARB'])

    global glCompressedTexSubImage3D
    glCompressedTexSubImage3D = <glCompressedTexSubImage3D_type> find_gl_command([b'glCompressedTexSubImage3D', b'glCompressedTexSubImage3DARB'])

    global glCopyTexImage2D
    glCopyTexImage2D = <glCopyTexImage2D_type> find_gl_command([b'glCopyTexImage2D', b'glCopyTexImage2DEXT'])

    global glCopyTexSubImage2D
    glCopyTexSubImage2D = <glCopyTexSubImage2D_type> find_gl_command([b'glCopyTexSubImage2D', b'glCopyTexSubImage2DEXT'])

    global glCopyTexSubImage3D
    glCopyTexSubImage3D = <glCopyTexSubImage3D_type> find_gl_command([b'glCopyTexSubImage3D', b'glCopyTexSubImage3DEXT'])

    global glCreateProgram
    glCreateProgram = <glCreateProgram_type> find_gl_command([b'glCreateProgram', b'glCreateProgramObjectARB'])

    global glCreateShader
    glCreateShader = <glCreateShader_type> find_gl_command([b'glCreateShader', b'glCreateShaderObjectARB'])

    global glCullFace
    glCullFace = <glCullFace_type> find_gl_command([b'glCullFace'])

    global glDeleteBuffers
    glDeleteBuffers = <glDeleteBuffers_type> find_gl_command([b'glDeleteBuffers', b'glDeleteBuffersARB'])

    global glDeleteFramebuffers
    glDeleteFramebuffers = <glDeleteFramebuffers_type> find_gl_command([b'glDeleteFramebuffers', b'glDeleteFramebuffersEXT'])

    global glDeleteProgram
    glDeleteProgram = <glDeleteProgram_type> find_gl_command([b'glDeleteProgram'])

    global glDeleteQueries
    glDeleteQueries = <glDeleteQueries_type> find_gl_command([b'glDeleteQueries', b'glDeleteQueriesARB'])

    global glDeleteRenderbuffers
    glDeleteRenderbuffers = <glDeleteRenderbuffers_type> find_gl_command([b'glDeleteRenderbuffers', b'glDeleteRenderbuffersEXT'])

    global glDeleteShader
    glDeleteShader = <glDeleteShader_type> find_gl_command([b'glDeleteShader'])

    global glDeleteTextures
    glDeleteTextures = <glDeleteTextures_type> find_gl_command([b'glDeleteTextures'])

    global glDeleteVertexArrays
    glDeleteVertexArrays = <glDeleteVertexArrays_type> find_gl_command([b'glDeleteVertexArrays', b'glDeleteVertexArraysAPPLE', b'glDeleteVertexArraysOES'])

    global glDepthFunc
    glDepthFunc = <glDepthFunc_type> find_gl_command([b'glDepthFunc'])

    global glDepthMask
    glDepthMask = <glDepthMask_type> find_gl_command([b'glDepthMask'])

    global glDetachShader
    glDetachShader = <glDetachShader_type> find_gl_command([b'glDetachShader'])

    global glDisable
    glDisable = <glDisable_type> find_gl_command([b'glDisable'])

    global glDisableVertexAttribArray
    glDisableVertexAttribArray = <glDisableVertexAttribArray_type> find_gl_command([b'glDisableVertexAttribArray', b'glDisableVertexAttribArrayARB'])

    global glDrawArrays
    glDrawArrays = <glDrawArrays_type> find_gl_command([b'glDrawArrays', b'glDrawArraysEXT'])

    global glDrawBuffers
    glDrawBuffers = <glDrawBuffers_type> find_gl_command([b'glDrawBuffers', b'glDrawBuffersARB', b'glDrawBuffersATI', b'glDrawBuffersEXT'])

    global glDrawElements
    glDrawElements = <glDrawElements_type> find_gl_command([b'glDrawElements'])

    global glDrawRangeElements
    glDrawRangeElements = <glDrawRangeElements_type> find_gl_command([b'glDrawRangeElements', b'glDrawRangeElementsEXT'])

    global glEnable
    glEnable = <glEnable_type> find_gl_command([b'glEnable'])

    global glEnableVertexAttribArray
    glEnableVertexAttribArray = <glEnableVertexAttribArray_type> find_gl_command([b'glEnableVertexAttribArray', b'glEnableVertexAttribArrayARB'])

    global glEndQuery
    glEndQuery = <glEndQuery_type> find_gl_command([b'glEndQuery', b'glEndQueryARB'])

    global glEndTransformFeedback
    glEndTransformFeedback = <glEndTransformFeedback_type> find_gl_command([b'glEndTransformFeedback', b'glEndTransformFeedbackEXT', b'glEndTransformFeedbackNV'])

    global glFinish
    glFinish = <glFinish_type> find_gl_command([b'glFinish'])

    global glFlush
    glFlush = <glFlush_type> find_gl_command([b'glFlush'])

    global glFlushMappedBufferRange
    glFlushMappedBufferRange = <glFlushMappedBufferRange_type> find_gl_command([b'glFlushMappedBufferRange', b'glFlushMappedBufferRangeAPPLE', b'glFlushMappedBufferRangeEXT'])

    global glFramebufferRenderbuffer
    glFramebufferRenderbuffer = <glFramebufferRenderbuffer_type> find_gl_command([b'glFramebufferRenderbuffer', b'glFramebufferRenderbufferEXT'])

    global glFramebufferTexture2D
    glFramebufferTexture2D = <glFramebufferTexture2D_type> find_gl_command([b'glFramebufferTexture2D', b'glFramebufferTexture2DEXT'])

    global glFramebufferTextureLayer
    glFramebufferTextureLayer = <glFramebufferTextureLayer_type> find_gl_command([b'glFramebufferTextureLayer', b'glFramebufferTextureLayerARB', b'glFramebufferTextureLayerEXT'])

    global glFrontFace
    glFrontFace = <glFrontFace_type> find_gl_command([b'glFrontFace'])

    global glGenBuffers
    glGenBuffers = <glGenBuffers_type> find_gl_command([b'glGenBuffers', b'glGenBuffersARB'])

    global glGenFramebuffers
    glGenFramebuffers = <glGenFramebuffers_type> find_gl_command([b'glGenFramebuffers', b'glGenFramebuffersEXT'])

    global glGenQueries
    glGenQueries = <glGenQueries_type> find_gl_command([b'glGenQueries', b'glGenQueriesARB'])

    global glGenRenderbuffers
    glGenRenderbuffers = <glGenRenderbuffers_type> find_gl_command([b'glGenRenderbuffers', b'glGenRenderbuffersEXT'])

    global glGenTextures
    glGenTextures = <glGenTextures_type> find_gl_command([b'glGenTextures'])

    global glGenVertexArrays
    glGenVertexArrays = <glGenVertexArrays_type> find_gl_command([b'glGenVertexArrays', b'glGenVertexArraysAPPLE', b'glGenVertexArraysOES'])

    global glGenerateMipmap
    glGenerateMipmap = <glGenerateMipmap_type> find_gl_command([b'glGenerateMipmap', b'glGenerateMipmapEXT'])

    global glGetActiveAttrib
    glGetActiveAttrib = <glGetActiveAttrib_type> find_gl_command([b'glGetActiveAttrib', b'glGetActiveAttribARB'])

    global glGetActiveUniform
    glGetActiveUniform = <glGetActiveUniform_type> find_gl_command([b'glGetActiveUniform', b'glGetActiveUniformARB'])

    global glGetAttachedShaders
    glGetAttachedShaders = <glGetAttachedShaders_type> find_gl_command([b'glGetAttachedShaders'])

    global glGetAttribLocation
    glGetAttribLocation = <glGetAttribLocation_type> find_gl_command([b'glGetAttribLocation', b'glGetAttribLocationARB'])

    global glGetBooleanv
    glGetBooleanv = <glGetBooleanv_type> find_gl_command([b'glGetBooleanv'])

    global glGetBufferParameteriv
    glGetBufferParameteriv = <glGetBufferParameteriv_type> find_gl_command([b'glGetBufferParameteriv', b'glGetBufferParameterivARB'])

    global glGetBufferPointerv
    glGetBufferPointerv = <glGetBufferPointerv_type> find_gl_command([b'glGetBufferPointerv', b'glGetBufferPointervARB', b'glGetBufferPointervOES'])

    global glGetError
    glGetError = <glGetError_type> find_gl_command([b'glGetError'])

    global glGetFloatv
    glGetFloatv = <glGetFloatv_type> find_gl_command([b'glGetFloatv'])

    global glGetFragDataLocation
    glGetFragDataLocation = <glGetFragDataLocation_type> find_gl_command([b'glGetFragDataLocation', b'glGetFragDataLocationEXT'])

    global glGetFramebufferAttachmentParameteriv
    glGetFramebufferAttachmentParameteriv = <glGetFramebufferAttachmentParameteriv_type> find_gl_command([b'glGetFramebufferAttachmentParameteriv', b'glGetFramebufferAttachmentParameterivEXT'])

    global glGetIntegeri_v
    glGetIntegeri_v = <glGetIntegeri_v_type> find_gl_command([b'glGetIntegeri_v', b'glGetIntegerIndexedvEXT'])

    global glGetIntegerv
    glGetIntegerv = <glGetIntegerv_type> find_gl_command([b'glGetIntegerv'])

    global glGetProgramInfoLog
    glGetProgramInfoLog = <glGetProgramInfoLog_type> find_gl_command([b'glGetProgramInfoLog'])

    global glGetProgramiv
    glGetProgramiv = <glGetProgramiv_type> find_gl_command([b'glGetProgramiv'])

    global glGetQueryObjectuiv
    glGetQueryObjectuiv = <glGetQueryObjectuiv_type> find_gl_command([b'glGetQueryObjectuiv', b'glGetQueryObjectuivARB'])

    global glGetQueryiv
    glGetQueryiv = <glGetQueryiv_type> find_gl_command([b'glGetQueryiv', b'glGetQueryivARB'])

    global glGetRenderbufferParameteriv
    glGetRenderbufferParameteriv = <glGetRenderbufferParameteriv_type> find_gl_command([b'glGetRenderbufferParameteriv', b'glGetRenderbufferParameterivEXT'])

    global glGetShaderInfoLog
    glGetShaderInfoLog = <glGetShaderInfoLog_type> find_gl_command([b'glGetShaderInfoLog'])

    global glGetShaderSource
    glGetShaderSource = <glGetShaderSource_type> find_gl_command([b'glGetShaderSource', b'glGetShaderSourceARB'])

    global glGetShaderiv
    glGetShaderiv = <glGetShaderiv_type> find_gl_command([b'glGetShaderiv'])

    global glGetString
    glGetString = <glGetString_type> find_gl_command([b'glGetString'])

    global glGetStringi
    glGetStringi = <glGetStringi_type> find_gl_command([b'glGetStringi'])

    global glGetTexParameterfv
    glGetTexParameterfv = <glGetTexParameterfv_type> find_gl_command([b'glGetTexParameterfv'])

    global glGetTexParameteriv
    glGetTexParameteriv = <glGetTexParameteriv_type> find_gl_command([b'glGetTexParameteriv'])

    global glGetTransformFeedbackVarying
    glGetTransformFeedbackVarying = <glGetTransformFeedbackVarying_type> find_gl_command([b'glGetTransformFeedbackVarying', b'glGetTransformFeedbackVaryingEXT'])

    global glGetUniformLocation
    glGetUniformLocation = <glGetUniformLocation_type> find_gl_command([b'glGetUniformLocation', b'glGetUniformLocationARB'])

    global glGetUniformfv
    glGetUniformfv = <glGetUniformfv_type> find_gl_command([b'glGetUniformfv', b'glGetUniformfvARB'])

    global glGetUniformiv
    glGetUniformiv = <glGetUniformiv_type> find_gl_command([b'glGetUniformiv', b'glGetUniformivARB'])

    global glGetUniformuiv
    glGetUniformuiv = <glGetUniformuiv_type> find_gl_command([b'glGetUniformuiv', b'glGetUniformuivEXT'])

    global glGetVertexAttribIiv
    glGetVertexAttribIiv = <glGetVertexAttribIiv_type> find_gl_command([b'glGetVertexAttribIiv', b'glGetVertexAttribIivEXT'])

    global glGetVertexAttribIuiv
    glGetVertexAttribIuiv = <glGetVertexAttribIuiv_type> find_gl_command([b'glGetVertexAttribIuiv', b'glGetVertexAttribIuivEXT'])

    global glGetVertexAttribPointerv
    glGetVertexAttribPointerv = <glGetVertexAttribPointerv_type> find_gl_command([b'glGetVertexAttribPointerv', b'glGetVertexAttribPointervARB', b'glGetVertexAttribPointervNV'])

    global glGetVertexAttribfv
    glGetVertexAttribfv = <glGetVertexAttribfv_type> find_gl_command([b'glGetVertexAttribfv', b'glGetVertexAttribfvARB', b'glGetVertexAttribfvNV'])

    global glGetVertexAttribiv
    glGetVertexAttribiv = <glGetVertexAttribiv_type> find_gl_command([b'glGetVertexAttribiv', b'glGetVertexAttribivARB', b'glGetVertexAttribivNV'])

    global glHint
    glHint = <glHint_type> find_gl_command([b'glHint'])

    global glIsBuffer
    glIsBuffer = <glIsBuffer_type> find_gl_command([b'glIsBuffer', b'glIsBufferARB'])

    global glIsEnabled
    glIsEnabled = <glIsEnabled_type> find_gl_command([b'glIsEnabled'])

    global glIsFramebuffer
    glIsFramebuffer = <glIsFramebuffer_type> find_gl_command([b'glIsFramebuffer', b'glIsFramebufferEXT'])

    global glIsProgram
    glIsProgram = <glIsProgram_type> find_gl_command([b'glIsProgram'])

    global glIsQuery
    glIsQuery = <glIsQuery_type> find_gl_command([b'glIsQuery', b'glIsQueryARB'])

    global glIsRenderbuffer
    glIsRenderbuffer = <glIsRenderbuffer_type> find_gl_command([b'glIsRenderbuffer', b'glIsRenderbufferEXT'])

    global glIsShader
    glIsShader = <glIsShader_type> find_gl_command([b'glIsShader'])

    global glIsTexture
    glIsTexture = <glIsTexture_type> find_gl_command([b'glIsTexture'])

    global glIsVertexArray
    glIsVertexArray = <glIsVertexArray_type> find_gl_command([b'glIsVertexArray', b'glIsVertexArrayAPPLE', b'glIsVertexArrayOES'])

    global glLineWidth
    glLineWidth = <glLineWidth_type> find_gl_command([b'glLineWidth'])

    global glLinkProgram
    glLinkProgram = <glLinkProgram_type> find_gl_command([b'glLinkProgram', b'glLinkProgramARB'])

    global glMapBufferRange
    glMapBufferRange = <glMapBufferRange_type> find_gl_command([b'glMapBufferRange', b'glMapBufferRangeEXT'])

    global glPixelStorei
    glPixelStorei = <glPixelStorei_type> find_gl_command([b'glPixelStorei'])

    global glPolygonOffset
    glPolygonOffset = <glPolygonOffset_type> find_gl_command([b'glPolygonOffset'])

    global glReadBuffer
    glReadBuffer = <glReadBuffer_type> find_gl_command([b'glReadBuffer'])

    global glReadPixels
    glReadPixels = <glReadPixels_type> find_gl_command([b'glReadPixels'])

    global glRenderbufferStorage
    glRenderbufferStorage = <glRenderbufferStorage_type> find_gl_command([b'glRenderbufferStorage', b'glRenderbufferStorageEXT'])

    global glRenderbufferStorageMultisample
    glRenderbufferStorageMultisample = <glRenderbufferStorageMultisample_type> find_gl_command([b'glRenderbufferStorageMultisample', b'glRenderbufferStorageMultisampleEXT', b'glRenderbufferStorageMultisampleNV'])

    global glSampleCoverage
    glSampleCoverage = <glSampleCoverage_type> find_gl_command([b'glSampleCoverage', b'glSampleCoverageARB'])

    global glScissor
    glScissor = <glScissor_type> find_gl_command([b'glScissor'])

    global glShaderSource
    glShaderSource = <glShaderSource_type> find_gl_command([b'glShaderSource', b'glShaderSourceARB'])

    global glStencilFunc
    glStencilFunc = <glStencilFunc_type> find_gl_command([b'glStencilFunc'])

    global glStencilFuncSeparate
    glStencilFuncSeparate = <glStencilFuncSeparate_type> find_gl_command([b'glStencilFuncSeparate'])

    global glStencilMask
    glStencilMask = <glStencilMask_type> find_gl_command([b'glStencilMask'])

    global glStencilMaskSeparate
    glStencilMaskSeparate = <glStencilMaskSeparate_type> find_gl_command([b'glStencilMaskSeparate'])

    global glStencilOp
    glStencilOp = <glStencilOp_type> find_gl_command([b'glStencilOp'])

    global glStencilOpSeparate
    glStencilOpSeparate = <glStencilOpSeparate_type> find_gl_command([b'glStencilOpSeparate', b'glStencilOpSeparateATI'])

    global glTexImage2D
    glTexImage2D = <glTexImage2D_type> find_gl_command([b'glTexImage2D'])

    global glTexImage3D
    glTexImage3D = <glTexImage3D_type> find_gl_command([b'glTexImage3D', b'glTexImage3DEXT'])

    global glTexParameterf
    glTexParameterf = <glTexParameterf_type> find_gl_command([b'glTexParameterf'])

    global glTexParameterfv
    glTexParameterfv = <glTexParameterfv_type> find_gl_command([b'glTexParameterfv'])

    global glTexParameteri
    glTexParameteri = <glTexParameteri_type> find_gl_command([b'glTexParameteri'])

    global glTexParameteriv
    glTexParameteriv = <glTexParameteriv_type> find_gl_command([b'glTexParameteriv'])

    global glTexSubImage2D
    glTexSubImage2D = <glTexSubImage2D_type> find_gl_command([b'glTexSubImage2D', b'glTexSubImage2DEXT'])

    global glTexSubImage3D
    glTexSubImage3D = <glTexSubImage3D_type> find_gl_command([b'glTexSubImage3D', b'glTexSubImage3DEXT'])

    global glTransformFeedbackVaryings
    glTransformFeedbackVaryings = <glTransformFeedbackVaryings_type> find_gl_command([b'glTransformFeedbackVaryings', b'glTransformFeedbackVaryingsEXT'])

    global glUniform1f
    glUniform1f = <glUniform1f_type> find_gl_command([b'glUniform1f', b'glUniform1fARB'])

    global glUniform1fv
    glUniform1fv = <glUniform1fv_type> find_gl_command([b'glUniform1fv', b'glUniform1fvARB'])

    global glUniform1i
    glUniform1i = <glUniform1i_type> find_gl_command([b'glUniform1i', b'glUniform1iARB'])

    global glUniform1iv
    glUniform1iv = <glUniform1iv_type> find_gl_command([b'glUniform1iv', b'glUniform1ivARB'])

    global glUniform1ui
    glUniform1ui = <glUniform1ui_type> find_gl_command([b'glUniform1ui', b'glUniform1uiEXT'])

    global glUniform1uiv
    glUniform1uiv = <glUniform1uiv_type> find_gl_command([b'glUniform1uiv', b'glUniform1uivEXT'])

    global glUniform2f
    glUniform2f = <glUniform2f_type> find_gl_command([b'glUniform2f', b'glUniform2fARB'])

    global glUniform2fv
    glUniform2fv = <glUniform2fv_type> find_gl_command([b'glUniform2fv', b'glUniform2fvARB'])

    global glUniform2i
    glUniform2i = <glUniform2i_type> find_gl_command([b'glUniform2i', b'glUniform2iARB'])

    global glUniform2iv
    glUniform2iv = <glUniform2iv_type> find_gl_command([b'glUniform2iv', b'glUniform2ivARB'])

    global glUniform2ui
    glUniform2ui = <glUniform2ui_type> find_gl_command([b'glUniform2ui', b'glUniform2uiEXT'])

    global glUniform2uiv
    glUniform2uiv = <glUniform2uiv_type> find_gl_command([b'glUniform2uiv', b'glUniform2uivEXT'])

    global glUniform3f
    glUniform3f = <glUniform3f_type> find_gl_command([b'glUniform3f', b'glUniform3fARB'])

    global glUniform3fv
    glUniform3fv = <glUniform3fv_type> find_gl_command([b'glUniform3fv', b'glUniform3fvARB'])

    global glUniform3i
    glUniform3i = <glUniform3i_type> find_gl_command([b'glUniform3i', b'glUniform3iARB'])

    global glUniform3iv
    glUniform3iv = <glUniform3iv_type> find_gl_command([b'glUniform3iv', b'glUniform3ivARB'])

    global glUniform3ui
    glUniform3ui = <glUniform3ui_type> find_gl_command([b'glUniform3ui', b'glUniform3uiEXT'])

    global glUniform3uiv
    glUniform3uiv = <glUniform3uiv_type> find_gl_command([b'glUniform3uiv', b'glUniform3uivEXT'])

    global glUniform4f
    glUniform4f = <glUniform4f_type> find_gl_command([b'glUniform4f', b'glUniform4fARB'])

    global glUniform4fv
    glUniform4fv = <glUniform4fv_type> find_gl_command([b'glUniform4fv', b'glUniform4fvARB'])

    global glUniform4i
    glUniform4i = <glUniform4i_type> find_gl_command([b'glUniform4i', b'glUniform4iARB'])

    global glUniform4iv
    glUniform4iv = <glUniform4iv_type> find_gl_command([b'glUniform4iv', b'glUniform4ivARB'])

    global glUniform4ui
    glUniform4ui = <glUniform4ui_type> find_gl_command([b'glUniform4ui', b'glUniform4uiEXT'])

    global glUniform4uiv
    glUniform4uiv = <glUniform4uiv_type> find_gl_command([b'glUniform4uiv', b'glUniform4uivEXT'])

    global glUniformMatrix2fv
    glUniformMatrix2fv = <glUniformMatrix2fv_type> find_gl_command([b'glUniformMatrix2fv', b'glUniformMatrix2fvARB'])

    global glUniformMatrix2x3fv
    glUniformMatrix2x3fv = <glUniformMatrix2x3fv_type> find_gl_command([b'glUniformMatrix2x3fv', b'glUniformMatrix2x3fvNV'])

    global glUniformMatrix2x4fv
    glUniformMatrix2x4fv = <glUniformMatrix2x4fv_type> find_gl_command([b'glUniformMatrix2x4fv', b'glUniformMatrix2x4fvNV'])

    global glUniformMatrix3fv
    glUniformMatrix3fv = <glUniformMatrix3fv_type> find_gl_command([b'glUniformMatrix3fv', b'glUniformMatrix3fvARB'])

    global glUniformMatrix3x2fv
    glUniformMatrix3x2fv = <glUniformMatrix3x2fv_type> find_gl_command([b'glUniformMatrix3x2fv', b'glUniformMatrix3x2fvNV'])

    global glUniformMatrix3x4fv
    glUniformMatrix3x4fv = <glUniformMatrix3x4fv_type> find_gl_command([b'glUniformMatrix3x4fv', b'glUniformMatrix3x4fvNV'])

    global glUniformMatrix4fv
    glUniformMatrix4fv = <glUniformMatrix4fv_type> find_gl_command([b'glUniformMatrix4fv', b'glUniformMatrix4fvARB'])

    global glUniformMatrix4x2fv
    glUniformMatrix4x2fv = <glUniformMatrix4x2fv_type> find_gl_command([b'glUniformMatrix4x2fv', b'glUniformMatrix4x2fvNV'])

    global glUniformMatrix4x3fv
    glUniformMatrix4x3fv = <glUniformMatrix4x3fv_type> find_gl_command([b'glUniformMatrix4x3fv', b'glUniformMatrix4x3fvNV'])

    global glUnmapBuffer
    glUnmapBuffer = <glUnmapBuffer_type> find_gl_command([b'glUnmapBuffer', b'glUnmapBufferARB', b'glUnmapBufferOES'])

    global glUseProgram
    glUseProgram = <glUseProgram_type> find_gl_command([b'glUseProgram', b'glUseProgramObjectARB'])

    global glValidateProgram
    glValidateProgram = <glValidateProgram_type> find_gl_command([b'glValidateProgram', b'glValidateProgramARB'])

    global glVertexAttrib1f
    glVertexAttrib1f = <glVertexAttrib1f_type> find_gl_command([b'glVertexAttrib1f', b'glVertexAttrib1fARB', b'glVertexAttrib1fNV'])

    global glVertexAttrib1fv
    glVertexAttrib1fv = <glVertexAttrib1fv_type> find_gl_command([b'glVertexAttrib1fv', b'glVertexAttrib1fvARB', b'glVertexAttrib1fvNV'])

    global glVertexAttrib2f
    glVertexAttrib2f = <glVertexAttrib2f_type> find_gl_command([b'glVertexAttrib2f', b'glVertexAttrib2fARB', b'glVertexAttrib2fNV'])

    global glVertexAttrib2fv
    glVertexAttrib2fv = <glVertexAttrib2fv_type> find_gl_command([b'glVertexAttrib2fv', b'glVertexAttrib2fvARB', b'glVertexAttrib2fvNV'])

    global glVertexAttrib3f
    glVertexAttrib3f = <glVertexAttrib3f_type> find_gl_command([b'glVertexAttrib3f', b'glVertexAttrib3fARB', b'glVertexAttrib3fNV'])

    global glVertexAttrib3fv
    glVertexAttrib3fv = <glVertexAttrib3fv_type> find_gl_command([b'glVertexAttrib3fv', b'glVertexAttrib3fvARB', b'glVertexAttrib3fvNV'])

    global glVertexAttrib4f
    glVertexAttrib4f = <glVertexAttrib4f_type> find_gl_command([b'glVertexAttrib4f', b'glVertexAttrib4fARB', b'glVertexAttrib4fNV'])

    global glVertexAttrib4fv
    glVertexAttrib4fv = <glVertexAttrib4fv_type> find_gl_command([b'glVertexAttrib4fv', b'glVertexAttrib4fvARB', b'glVertexAttrib4fvNV'])

    global glVertexAttribI4i
    glVertexAttribI4i = <glVertexAttribI4i_type> find_gl_command([b'glVertexAttribI4i', b'glVertexAttribI4iEXT'])

    global glVertexAttribI4iv
    glVertexAttribI4iv = <glVertexAttribI4iv_type> find_gl_command([b'glVertexAttribI4iv', b'glVertexAttribI4ivEXT'])

    global glVertexAttribI4ui
    glVertexAttribI4ui = <glVertexAttribI4ui_type> find_gl_command([b'glVertexAttribI4ui', b'glVertexAttribI4uiEXT'])

    global glVertexAttribI4uiv
    glVertexAttribI4uiv = <glVertexAttribI4uiv_type> find_gl_command([b'glVertexAttribI4uiv', b'glVertexAttribI4uivEXT'])

    global glVertexAttribIPointer
    glVertexAttribIPointer = <glVertexAttribIPointer_type> find_gl_command([b'glVertexAttribIPointer', b'glVertexAttribIPointerEXT'])

    global glVertexAttribPointer
    glVertexAttribPointer = <glVertexAttribPointer_type> find_gl_command([b'glVertexAttribPointer', b'glVertexAttribPointerARB'])

    global glViewport
    glViewport = <glViewport_type> find_gl_command([b'glViewport'])
