version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    target-branch: "fix"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "04:00"
      timezone: "UTC"

  - package-ecosystem: "pip"
    directory: "/"
    target-branch: "master"
    schedule:
      interval: "weekly"
      day: "tuesday"
      time: "04:00"
      timezone: "UTC"
