# Copyright 2004-2026 Tom Rothamel <pytom@bishoujo.us>
#
# Permission is hereby granted, free of charge, to any person
# obtaining a copy of this software and associated documentation files
# (the "Software"), to deal in the Software without restriction,
# including without limitation the rights to use, copy, modify, merge,
# publish, distribute, sublicense, and/or sell copies of the Software,
# and to permit persons to whom the Software is furnished to do so,
# subject to the following conditions:
#
# The above copyright notice and this permission notice shall be
# included in all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
# EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
# MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
# NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE
# LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION
# OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION
# WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.


from __future__ import print_function

import renpy


def import_style_functions():
    import renpy.styledata.stylesets

    import renpy.styledata.style_functions
    import renpy.styledata.style_activate_functions
    import renpy.styledata.style_hover_functions
    import renpy.styledata.style_idle_functions
    import renpy.styledata.style_insensitive_functions

    import renpy.styledata.style_selected_functions
    import renpy.styledata.style_selected_activate_functions
    import renpy.styledata.style_selected_hover_functions
    import renpy.styledata.style_selected_idle_functions
    import renpy.styledata.style_selected_insensitive_functions

    import renpy.styledata.styleclass

    renpy.style.Style = renpy.styledata.styleclass.Style  # type: ignore


# Generated by scripts/relative_imports.py, do not edit below this line.
import typing

if typing.TYPE_CHECKING:
    from . import style_activate_functions as style_activate_functions
    from . import style_functions as style_functions
    from . import style_hover_functions as style_hover_functions
    from . import style_idle_functions as style_idle_functions
    from . import style_insensitive_functions as style_insensitive_functions
    from . import style_selected_activate_functions as style_selected_activate_functions
    from . import style_selected_functions as style_selected_functions
    from . import style_selected_hover_functions as style_selected_hover_functions
    from . import style_selected_idle_functions as style_selected_idle_functions
    from . import style_selected_insensitive_functions as style_selected_insensitive_functions
    from . import styleclass as styleclass
    from . import stylesets as stylesets
    from . import styleutil as styleutil
