# Generated by scripts/generate_pyi.py, do not edit.

from typing import Any, Callable

import renpy

import builtins as __builtins__

def get_embedding_levels(s, direction: int=FRIBIDI_TYPE_ON): ...

def log2vis(s, direction: int=FRIBIDI_TYPE_ON): ...

LTR: int
ON: int
RTL: int
WLTR: int
WRTL: int
