translate japanese python:
    LIGHT   = "../../tutorial/game/tl/japanese/MTLc3m.ttf"
    style.l_default.font = LIGHT                                                                                                   
    style.l_button_text.selected_font = LIGHT
    style.l_button_text.selected_bold = True
    style.l_link_text.font = LIGHT                                                                                                 
    style.l_alternate_text.font = LIGHT                                                                                            
    style.l_navigation_button_text.font = LIGHT
    style.l_navigation_text.font = LIGHT                                                                                           
    style.l_navigation_text.bold = True
    style.l_checkbox_text.selected_font = LIGHT                                                                                    
    style.l_nonbox_text.selected_font = LIGHT                                                                                      
    style.hyperlink_text.font = LIGHT                                                                                              
