/* Generated by Cython 3.2.1 */

#ifndef __PYX_HAVE_API__pygame__surface
#define __PYX_HAVE_API__pygame__surface
#ifdef __MINGW64__
#define MS_WIN64
#endif
#include "Python.h"

static struct SDL_Surface *(*__pyx_api_f_6pygame_7surface_PySurface_AsSurface)(PyObject *) = 0;
#define PySurface_AsSurface __pyx_api_f_6pygame_7surface_PySurface_AsSurface
static PyObject *(*__pyx_api_f_6pygame_7surface_PySurface_New)(struct SDL_Surface *) = 0;
#define PySurface_New __pyx_api_f_6pygame_7surface_PySurface_New
static int __Pyx_ImportFunction_3_2_1(PyObject *module, const char *funcname, void (**f)(void), const char *sig);

#ifndef __PYX_HAVE_RT_ImportFromPxd_3_2_1
#define __PYX_HAVE_RT_ImportFromPxd_3_2_1
static int __Pyx_ImportFromPxd_3_2_1(PyObject *module, const char *name, void **p, const char *sig, const char *what) {
    PyObject *d = 0;
    PyObject *cobj = 0;
    d = PyObject_GetAttrString(module, "__pyx_capi__");
    if (!d)
        goto bad;
#if (defined(Py_LIMITED_API) && Py_LIMITED_API >= 0x030d0000) || (!defined(Py_LIMITED_API) && PY_VERSION_HEX >= 0x030d0000)
    PyDict_GetItemStringRef(d, name, &cobj);
#else
    cobj = PyDict_GetItemString(d, name);
    Py_XINCREF(cobj);
#endif
    if (!cobj) {
        PyErr_Format(PyExc_ImportError,
            "%.200s does not export expected C %.8s %.200s",
                PyModule_GetName(module), what, name);
        goto bad;
    }
    if (!PyCapsule_IsValid(cobj, sig)) {
        PyErr_Format(PyExc_TypeError,
            "C %.8s %.200s.%.200s has wrong signature (expected %.500s, got %.500s)",
             what, PyModule_GetName(module), name, sig, PyCapsule_GetName(cobj));
        goto bad;
    }
    *p = PyCapsule_GetPointer(cobj, sig);
    if (!(*p))
        goto bad;
    Py_DECREF(d);
    Py_DECREF(cobj);
    return 0;
bad:
    Py_XDECREF(d);
    Py_XDECREF(cobj);
    return -1;
}
#endif

#ifndef __PYX_HAVE_RT_ImportFunction_3_2_1
#define __PYX_HAVE_RT_ImportFunction_3_2_1
static int __Pyx_ImportFunction_3_2_1(PyObject *module, const char *funcname, void (**f)(void), const char *sig) {
    union {
        void (*fp)(void);
        void *p;
    } tmp;
    int result = __Pyx_ImportFromPxd_3_2_1(module, funcname, &tmp.p, sig, "function");
    if (result == 0) {
        *f = tmp.fp;
    }
    return result;
}
#endif


static int import_pygame__surface(void) {
  PyObject *module = 0;
  module = PyImport_ImportModule("pygame.surface");
  if (!module) goto bad;
  if (__Pyx_ImportFunction_3_2_1(module, "PySurface_AsSurface", (void (**)(void))&__pyx_api_f_6pygame_7surface_PySurface_AsSurface, "struct SDL_Surface *(PyObject *)") < 0) goto bad;
  if (__Pyx_ImportFunction_3_2_1(module, "PySurface_New", (void (**)(void))&__pyx_api_f_6pygame_7surface_PySurface_New, "PyObject *(struct SDL_Surface *)") < 0) goto bad;
  Py_DECREF(module); module = 0;
  return 0;
  bad:
  Py_XDECREF(module);
  return -1;
}

#endif /* !__PYX_HAVE_API__pygame__surface */
