name: Test

on:
  push:
    branches: [master, fix]
  pull_request:
  workflow_dispatch:

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5
    env:
      RENPY_CC: "sccache gcc"
      RENPY_LD: "sccache gcc"
      SCCACHE_GHA_ENABLED: "true"
    steps:
    - uses: actions/checkout@v4
    - name: Run sccache-cache
      uses: mozilla-actions/sccache-action@v0.0.10
    - name: Set up Python 3.12
      uses: actions/setup-python@v3
      with:
        python-version: '3.12'
    - run: |
        sudo apt install python3-dev libassimp-dev libavcodec-dev libavformat-dev \
        libswresample-dev libswscale-dev libharfbuzz-dev libfreetype6-dev libfribidi-dev libsdl2-dev \
        libsdl2-image-dev libsdl2-gfx-dev libsdl2-mixer-dev libsdl2-ttf-dev libjpeg-dev pkg-config
    - name: Install the latest version of uv
      uses: astral-sh/setup-uv@08807647e7069bb48b6ef5acd8ec9567f424441b # v8.1.0
    - run: uv sync
    - run: ./run.sh --build
    - run: ./run.sh ./testcases/game test
